# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Distribute build with app distribution"
  lane :distribute do
    gradle(task: "clean assembleDebug")

    firebase_app_distribution(
        app: "1:77202193010:android:9445c2e6f55bde10ef20eb",
        debug: true
    )
  end
end
