
default_platform(:ios)

platform :ios do
  lane :build_adhoc do
      puts "Building adhoc app..."
      team_id("L8VKXC2S77")
      match(
          username: "fad-fastlane@google.com",
          app_identifier: "dev.firebase.Bee-Plus",
	  type: "adhoc"
      )
      gym(
          scheme: "Bee Plus",
          output_name: "Bee Plus Adhoc"
      )
  end

  lane :build_enterprise do
      puts "Building enterprise app..."
      team_id("FCAH69RY2W")
      match(
          username: "fad-fastlane@google.com",
          app_identifier: "dev.firebase.Bee-Plus-Enterprise",
          type: "enterprise"
      )
      gym(
          scheme: "Bee Plus Enterprise",
          export_method: "enterprise",
          output_name: "Bee Plus Enterprise"
      )
  end

  lane :fad_distribute do |options|
      if options[:type] == 'enterprise'
          build_enterprise
          puts "Distributing enterprise app to App Distribution..."
      else
  	  build_adhoc
          puts "Distributing adhoc app to App Distribution..."
      end

      firebase_app_distribution(
          app: "1:461235515410:ios:bcc2b167a9d6b3e0bfe8cb",
          testers: "mallardcrash@gmail.com",
          release_notes: options[:release_notes]      
      )
  end
end
