# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Builds app for FAD distribution"
  lane :fad_adhoc do
      team_id("L8VKXC2S77")
      match(
          username: "fad-fastlane@google.com",
          app_identifier: "dev.firebase.Bee-Plus",
	  type: "adhoc"
      )
      gym(
          scheme: "Bee Plus",
          output_name: "Bee Plus Adhoc"
      )
  end

  lane :fad_enterprise do
      team_id("FCAH69RY2W")
      match(
          username: "fad-fastlane@google.com",
          app_identifier: "dev.firebase.Bee-Plus-Enterprise",
          type: "enterprise"
      )
      gym(
          scheme: "Bee Plus Enterprise",
          export_method: "enterprise",
          output_name: "Bee Plus Enterprise"
      )
  end
end
