platform :ios, '12.1'

target 'Bee Plus' do
  use_frameworks!

  pod 'Firebase/AppDistribution'
  pod 'GoogleSignIn', '~> 5.0'
  pod 'RevealingSplashView'

  target 'Bee PlusTests' do
    inherit! :search_paths
  end

  target 'Bee PlusUITests' do
    inherit! :search_paths
  end

end

