platform :ios, '12.1'

target 'Bee Plus' do
  use_frameworks!

  pod 'FirebaseAppDistribution'
  pod 'GoogleSignIn'
  pod 'RevealingSplashView'

  target 'Bee PlusTests' do
    inherit! :search_paths
  end

  target 'Bee PlusUITests' do
    inherit! :search_paths
  end

end

