platform :ios, '12.1'

target 'Bee Plus' do
  use_frameworks!

  pod 'FirebaseAppDistribution', :git => 'https://github.com/firebase/firebase-ios-sdk.git'
  pod 'GoogleSignIn'
  pod 'RevealingSplashView'

  target 'Bee PlusTests' do
    inherit! :search_paths
  end

  target 'Bee PlusUITests' do
    inherit! :search_paths
  end

end
