#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Wed Jan 16 14:51:46 EST 2019
apiSecret=ae173ed392cb6dc7ab8c901af5583679364545d4c9052159dcfa70f6b85b98f7
