#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Tue Oct 30 13:47:40 EDT 2018
apiSecret=9e504964099cc470da2b5315d4ecd9a5aaaf896e297c17b29c3a7f19e2b58736
