apply plugin: 'com.android.application'
apply plugin: 'com.google.firebase.appdistribution'

android {
    compileSdkVersion 33
    defaultConfig {
        applicationId "dev.firebase.beeplus"
        minSdkVersion 19
        targetSdkVersion 33
        versionCode 3
        versionName "3.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            firebaseAppDistribution {
                appId="1:461235515410:android:c883034d281eb56a"
                artifactType="APK"
                releaseNotes="hi"
                testers="abarone@google.com"
                groups="mallard-group"
            }
        }
        debug {
            firebaseAppDistribution {
                // This app has AAB uploads enabled
                appId="1:1095562434941:android:502210c4f11e5466269414"
                testCases="case1,case2"
                testDevices="model=MediumPhone.arm,version=34,orientation=portrait,locale=en_US"
            }
        }
    }
    namespace 'dev.firebase.beeplus'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation 'com.google.firebase:firebase-auth:16.1.0'
    implementation 'com.google.android.gms:play-services-auth:16.0.1'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.android.support:cardview-v7:26.1.0'
}

apply plugin: 'com.google.gms.google-services'
